0.137232
0.400944
0.477397
0.513401
0.526745
0.606969
0.635712
0.637552
0.76823
0.807725
0.839112
0.891529
0.911647
0.949327
0.972775
0.998925
100
Called start for 6 0.137232
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Called start for 7 0.400944
Called start for 2 0.477397
Called start for 3 0.513401
Called stop for 6 0.51735
Called start for 12 0.526745
Called start for 5 0.606969
Called start for 4 0.635712
Called start for 10 0.637552
Called start for 1 0.76823
Node handle called for 7
Called start for 14 0.807725
Node handle called for 7
Node handle called for 7
Node handle called for 7
Node handle called for 7
Called start for 9 0.839112
Called start for 13 0.891529
Called start for 0 0.911647
Called start for 15 0.949327
Node handle called for 2
Called stop for 7 0.958568
Node handle called for 2
Node handle called for 2
Node handle called for 2
Called start for 11 0.972775
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Called start for 8 0.998925
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Called start for 6 1.051
Node handle called for 3
Node handle called for 3
Node handle called for 12
Node handle called for 3
Node handle called for 12
Node handle called for 3
Node handle called for 12
Node handle called for 3
Node handle called for 12
Node handle called for 3
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 5
Node handle called for 5
Node handle called for 5
Node handle called for 5
Node handle called for 4
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 10
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Called stop for 5 1.35554
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Called stop for 3 1.39159
Called stop for 2 1.50876
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Called stop for 10 1.57114
Node handle called for 1
Node handle called for 1
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Called stop for 12 1.82485
Node handle called for 13
Node handle called for 0
Node handle called for 13
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Called stop for 1 1.87168
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 15
Node handle called for 0
Node handle called for 15
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Called stop for 14 1.96791
Called stop for 15 1.96841
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 8
Node handle called for 11
Node handle called for 8
Node handle called for 11
Node handle called for 8
Node handle called for 6
Called stop for 8 2.10666
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Called stop for 13 2.18329
Called stop for 4 2.18762
Called stop for 9 2.19116
Called stop for 6 2.34489
Called stop for 11 2.43913
Called stop for 0 2.62173
Called start for 7 2.72131
Called start for 2 3.2953
Called start for 3 3.41204
Called start for 5 3.42838
Called start for 10 3.75491
Called start for 1 3.94092
Called start for 12 3.94221
Called start for 14 4.21913
Called start for 8 4.34311
Called start for 9 4.60057
Called start for 6 4.70608
Called start for 15 4.85585
Called start for 13 5.13649
Called start for 4 5.32747
Called start for 11 5.40255
Node handle called for 7
Node handle called for 7
Node handle called for 7
Node handle called for 7
Node handle called for 7
Called stop for 7 5.5993
Called start for 0 6.02657
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 5
Node handle called for 3
Node handle called for 5
Node handle called for 3
Node handle called for 5
Node handle called for 5
Called stop for 5 6.99836
Called stop for 2 7.14458
Called stop for 3 7.18887
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Called stop for 10 7.80586
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 1
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Called stop for 1 8.21705
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Called stop for 12 8.65578
Node handle called for 8
Node handle called for 8
Node handle called for 8
Called stop for 14 8.79072
Called stop for 8 8.79502
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Called stop for 6 9.65504
Called stop for 9 9.71407
Node handle called for 15
Node handle called for 15
Called stop for 15 9.78145
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Called stop for 13 10.6732
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Called stop for 11 11.2987
Called stop for 4 11.5711
Called start for 7 12.0028
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Called stop for 0 12.8516
Called start for 2 14.5669
Called start for 5 14.714
Called start for 3 15.0066
Called start for 10 16.2244
Called start for 1 16.6317
Called start for 12 17.6041
Called start for 8 17.7198
Called start for 14 17.8647
Called start for 6 19.3264
Called start for 9 19.6464
Called start for 15 20.4819
Called start for 13 22.1163
Called start for 11 23.1217
Node handle called for 7
Node handle called for 7
Node handle called for 7
Node handle called for 7
Node handle called for 7
Called start for 4 24.0945
Called stop for 7 24.1622
Called start for 0 26.4863
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 2
Node handle called for 5
Node handle called for 5
Node handle called for 5
Node handle called for 5
Called stop for 5 29.5696
Called stop for 2 29.6878
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Node handle called for 3
Called stop for 3 30.378
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Node handle called for 10
Called stop for 10 32.7447
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Node handle called for 1
Called stop for 1 33.5985
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 12
Node handle called for 8
Node handle called for 8
Node handle called for 8
Called stop for 8 35.5485
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Node handle called for 14
Called stop for 12 35.9795
Called stop for 14 36.082
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Node handle called for 6
Called stop for 6 38.8956
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Node handle called for 9
Called stop for 9 39.8057
Node handle called for 15
Node handle called for 15
Called stop for 15 41.0336
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Node handle called for 13
Called stop for 13 44.6329
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Node handle called for 11
Called stop for 11 46.7369
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Node handle called for 4
Called stop for 4 49.1052
Called start for 7 49.1287
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Node handle called for 0
Called stop for 0 53.7709
Called start for 2 59.6534
Called start for 5 59.8566
Called start for 3 61.3849
Called start for 10 66.1021
Called start for 1 67.3946
Called start for 8 71.2267
Called start for 12 72.2516
Called start for 14 72.4472
Called start for 6 77.8076
Called start for 9 79.8297
Called start for 15 82.9862
Called start for 13 90.0357
Called start for 11 93.9981
Node handle called for 7
Node handle called for 7
Node handle called for 7
Node handle called for 7
Node handle called for 7
Called stop for 7 98.414
Called start for 4 99.1626
Simuator stopped!!
